[{
    "company_name":"hcl",
    "date":ISODate("2020-09-25"),
    "students_appeared":"Dinesh,Chandran,raja,antony,fernando"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-16"),
    "students_appeared":"anabel,sanjay,Kumar,john,infant"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-27"),
    "students_appeared":"Chandran,Suresh,ashok,Ramesh,abi"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-11-15"),
    "students_appeared":"naveen,suvan,felix,jethro,ashwin"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-11-25"),
    "students_appeared":"jeshwin,prakash,rohit,yogesh,Suresh"
}]

